import { StampData } from '@/types/stamps';

/**
 * あおちゃんスタンプのデータ定義
 */
export const aoStamps: StampData[] = [
  {
    id: 'ao_hello',
    name: 'こんにちは！',
    nameEn: 'Hello!',
    emotion: 'happy',
    category: 'greeting',
    src: '/images/stamps/ao/ao_hello.png',
    srcRetina: '/images/stamps/retina/ao/ao_hello@2x.png',
    animation: 'bounce',
    sound: '/sounds/stamps/hello.mp3',
  },
  {
    id: 'ao_goodnight',
    name: 'おやすみ〜',
    nameEn: 'Good night',
    emotion: 'calm',
    category: 'greeting',
    src: '/images/stamps/ao/ao_goodnight.png',
    srcRetina: '/images/stamps/retina/ao/ao_goodnight@2x.png',
    animation: 'scale',
    sound: '/sounds/stamps/goodnight.mp3',
  },
  {
    id: 'ao_birthday',
    name: 'おたんじょうび',
    nameEn: 'Birthday!',
    emotion: 'excited',
    category: 'celebration',
    src: '/images/stamps/ao/ao_birthday.png',
    srcRetina: '/images/stamps/retina/ao/ao_birthday@2x.png',
    animation: 'bounce',
    sound: '/sounds/stamps/birthday.mp3',
  },
  {
    id: 'ao_yay',
    name: 'やったー！',
    nameEn: 'Yay!',
    emotion: 'excited',
    category: 'celebration',
    src: '/images/stamps/ao/ao_yay.png',
    srcRetina: '/images/stamps/retina/ao/ao_yay@2x.png',
    animation: 'shake',
    sound: '/sounds/stamps/yay.mp3',
  },
  {
    id: 'ao_love',
    name: 'だいすき♥',
    nameEn: 'Love you',
    emotion: 'happy',
    category: 'emotion',
    src: '/images/stamps/ao/ao_love.png',
    srcRetina: '/images/stamps/retina/ao/ao_love@2x.png',
    animation: 'scale',
    sound: '/sounds/stamps/love.mp3',
  },
  {
    id: 'ao_upset',
    name: 'ぷんぷん！',
    nameEn: 'Upset',
    emotion: 'sad',
    category: 'emotion',
    src: '/images/stamps/ao/ao_upset.png',
    srcRetina: '/images/stamps/retina/ao/ao_upset@2x.png',
    animation: 'shake',
    sound: '/sounds/stamps/upset.mp3',
  },
  {
    id: 'ao_thank_you',
    name: 'ありがとう',
    nameEn: 'Thank you',
    emotion: 'happy',
    category: 'greeting',
    src: '/images/stamps/ao/ao_thank_you.png',
    srcRetina: '/images/stamps/retina/ao/ao_thank_you@2x.png',
    animation: 'bounce',
    sound: '/sounds/stamps/thank_you.mp3',
  },
  {
    id: 'ao_ok',
    name: 'OK!',
    nameEn: 'OK!',
    emotion: 'happy',
    category: 'action',
    src: '/images/stamps/ao/ao_ok.png',
    srcRetina: '/images/stamps/retina/ao/ao_ok@2x.png',
    animation: 'scale',
    sound: '/sounds/stamps/ok.mp3',
  },
  {
    id: 'ao_present',
    name: 'Present!',
    nameEn: 'Present!',
    emotion: 'excited',
    category: 'celebration',
    src: '/images/stamps/ao/ao_present.png',
    srcRetina: '/images/stamps/retina/ao/ao_present@2x.png',
    animation: 'bounce',
    sound: '/sounds/stamps/present.mp3',
  },
  {
    id: 'ao_pet_me',
    name: 'なでて〜',
    nameEn: 'Pet me',
    emotion: 'calm',
    category: 'action',
    src: '/images/stamps/ao/ao_pet_me.png',
    srcRetina: '/images/stamps/retina/ao/ao_pet_me@2x.png',
    animation: 'scale',
    sound: '/sounds/stamps/pet_me.mp3',
  },
  {
    id: 'ao_excuse_me',
    name: 'おわかし',
    nameEn: 'Excuse me',
    emotion: 'surprised',
    category: 'emotion',
    src: '/images/stamps/ao/ao_excuse_me.png',
    srcRetina: '/images/stamps/retina/ao/ao_excuse_me@2x.png',
    animation: 'shake',
    sound: '/sounds/stamps/excuse_me.mp3',
  },
];